version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "📂 Estrutura de arquivos no CodeBuild:"
      - ls -R
      - echo "➡️ Rodando pipeline local no CodeBuild"
      - python aws_scrap_codebuild.py

artifacts:
  files:
    - '**/*'
