version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependências..."
      - pip install -r requirements.txt
      - echo "Instalando Google Chrome..."
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt update && apt install -y ./google-chrome-stable_current_amd64.deb
      - echo "Detectando versão do Chrome..."
      - CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
      - MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)
      - DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$MAJOR_VERSION")
      - echo "Versão do Chrome: $CHROME_VERSION"
      - echo "Versão do ChromeDriver: $DRIVER_VERSION"
      - wget "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
      - unzip chromedriver_linux64.zip
      - mv chromedriver /usr/bin/chromedriver
      - chmod +x /usr/bin/chromedriver

  build:
    commands:
      - echo "Executando scraper..."
      - python scraper.py

artifacts:
  files:
    - '**/*'
