version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependências..."
      - pip install -r requirements.txt

      - echo "Instalando Google Chrome..."
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt update && apt install -y ./google-chrome-stable_current_amd64.deb

      - echo "Instalando ChromeDriver versão fixa..."
      - wget -O chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/117.0.5938.92/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - mv chromedriver /usr/bin/chromedriver
      - chmod +x /usr/bin/chromedriver

  build:
    commands:
      - echo "Executando scraper..."
      - python scraper.py

artifacts:
  files:
    - '**/*'

