version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "➡️ Rodando pipeline local no CodeBuild"
      - python test_scrap/test_scrap_local.py

artifacts:
  files:
    - '**/*'